wdefault: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: uetphoto

test:
  <<: *default
  database: uetphoto

production:
  <<: *default
  database: uetphoto_production
  username: uetphoto
  password: <%= ENV["UETPHOTO_DATABASE_PASSWORD"] %>
